[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
known_first_party = ["src"]
